require("dotenv").config();
const {
    KAFKA_GROUP_ID,
    KAFKA_CLIENT_ID,
    KAFKA_BROKER,
    KAFKA_USERNAME,
    KAFKA_PASSWORD,
    KAFKA_TEST_TOPIC

} = process.env;

module.exports = {
    KAFKA_GROUP_ID: KAFKA_GROUP_ID,
    KAFKA_CLIENT_ID: KAFKA_CLIENT_ID,
    KAFKA_BROKER: KAFKA_BROKER,
    KAFKA_USERNAME: KAFKA_USERNAME,
    KAFKA_PASSWORD: KAFKA_PASSWORD,
    KAFKA_TEST_TOPIC: KAFKA_TEST_TOPIC
};